# Generated by Django 4.2.4 on 2023-08-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="nome",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="rg",
            field=models.CharField(
                blank=True, max_length=9, null=True, verbose_name="RG"
            ),
        ),
    ]
