# Generated by Django 4.2.2 on 2023-08-01 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("P10", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produtos",
            old_name="Nome",
            new_name="nome",
        ),
        migrations.AddField(
            model_name="produtos",
            name="capa",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="uploader.image",
            ),
        ),
    ]
