# Generated by Django 4.2.4 on 2023-09-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("P10", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=100)),
            ],
        ),
    ]
