# Generated by Django 4.2.2 on 2023-08-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("P10", "0002_rename_nome_produtos_nome_produtos_capa"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cnpj", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("telefone", models.CharField(max_length=100)),
                ("endereco", models.CharField(max_length=100)),
            ],
        ),
    ]
