# Generated by Django 4.2.4 on 2023-08-08 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("P10", "0002_compra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtos",
            name="desconto",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Produtos",
                to="P10.descontos",
            ),
        ),
    ]
