# Generated by Django 4.2.4 on 2023-09-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("P10", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="materialCommunityIcons",
            field=models.CharField(default=8, max_length=50),
            preserve_default=False,
        ),
    ]
