# Generated by Django 4.2.4 on 2023-09-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("P10", "0002_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produtos",
            name="tags",
        ),
        migrations.AddField(
            model_name="produtos",
            name="tag",
            field=models.ManyToManyField(related_name="Produtos", to="P10.tag"),
        ),
    ]
