# Generated by Django 4.2.2 on 2023-08-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("P10", "0003_fornecedor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fornecedor",
            name="cnpj",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="fornecedor",
            name="email",
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name="fornecedor",
            name="telefone",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
