# Generated by Django 4.2.4 on 2023-08-09 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("P10", "0004_alter_descontos_porcentagem_alter_produtos_desconto_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubCategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Cliente",
        ),
        migrations.AddField(
            model_name="produtos",
            name="subcategoria",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Produtos",
                to="P10.subcategoria",
            ),
        ),
    ]
