# Generated by Django 4.2.2 on 2023-08-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("P10", "0004_alter_fornecedor_cnpj_alter_fornecedor_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fornecedor",
            name="telefone",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
