# Generated by Django 4.2.4 on 2023-09-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("P10", "0005_alter_produtos_desconto_alter_produtos_sazonal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produtos",
            name="tags",
        ),
        migrations.AddField(
            model_name="produtos",
            name="tags",
            field=models.CharField(default=6, max_length=200),
            preserve_default=False,
        ),
    ]
