# Generated by Django 4.2.2 on 2023-08-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("P10", "0005_alter_fornecedor_telefone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fornecedor",
            name="telefone",
            field=models.CharField(max_length=100),
        ),
    ]
