# Generated by Django 4.2.4 on 2023-08-15 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("P10", "0005_subcategoria_delete_cliente_produtos_subcategoria"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="descontos",
            options={"verbose_name_plural": "Descontos"},
        ),
        migrations.AlterModelOptions(
            name="produtos",
            options={"verbose_name_plural": "Produtos"},
        ),
    ]
