# Generated by Django 4.2.4 on 2023-08-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("P10", "0007_sazonal"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sazonal",
            options={"verbose_name_plural": "Sazonais"},
        ),
        migrations.RenameField(
            model_name="sazonal",
            old_name="descrição",
            new_name="descricao",
        ),
        migrations.AddField(
            model_name="fornecedor",
            name="cep",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
