# Generated by Django 4.2.2 on 2023-08-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("P10", "0008_categoria"),
    ]

    operations = [
        migrations.CreateModel(
            name="Descontos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=100)),
                ("porcentagem", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
