# Generated by Django 4.2.4 on 2023-08-23 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("P10", "0009_remove_produtos_subcategoria_produtos_sazonal"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategoria",
            name="categoria",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subcategorias",
                to="P10.categoria",
            ),
        ),
        migrations.AlterField(
            model_name="produtos",
            name="desconto",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Produtos",
                to="P10.descontos",
            ),
        ),
    ]
