# Generated by Django 4.2.2 on 2023-08-04 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("P10", "0009_descontos"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fornecedor",
            options={"verbose_name_plural": "Fornecedores"},
        ),
        migrations.AlterField(
            model_name="produtos",
            name="fornecedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Produtos",
                to="P10.fornecedor",
            ),
        ),
    ]
