# Generated by Django 4.2.4 on 2023-08-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("P10", "0010_subcategoria_categoria_alter_produtos_desconto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produtos",
            name="capa",
        ),
        migrations.AddField(
            model_name="produtos",
            name="imagem",
            field=models.ManyToManyField(related_name="+", to="uploader.image"),
        ),
    ]
