# Generated by Django 4.2.2 on 2023-08-04 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("P10", "0010_alter_fornecedor_options_alter_produtos_fornecedor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produtos",
            old_name="Preço",
            new_name="preco",
        ),
    ]
