# Generated by Django 4.2.2 on 2023-08-04 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("P10", "0011_rename_preço_produtos_preco"),
    ]

    operations = [
        migrations.AddField(
            model_name="produtos",
            name="categoria",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Produtos",
                to="P10.categoria",
            ),
            preserve_default=False,
        ),
    ]
