# Generated by Django 4.2.4 on 2023-08-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("P10", "0011_remove_produtos_capa_produtos_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="itenscompra",
            name="preco_item",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
